
server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: admin123
    username: root
    url: jdbc:mysql://localhost:3306/staff_management_system?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
  #    url: jdbc:mysql://localhost:3306/blog?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379

    password:
    timeout: 10000
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



